# Generated by Django 5.0.4 on 2024-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
